mysql:
  db: chatnio
  host: free.clusters.zeabur.com
  password: BsSWnIK31HNpdolyV8064keam957uZ2D
  port: 31114
  user: root
  tls: false

redis:
  host: free.clusters.zeabur.com
  port: 32226
  db: 0
  password: "0EDAgsL6M5Zluq192fNWcwr8J47xjdO3"


secret: secret
serve_static: true

server:
  port: 8094
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
